###pip install numpy
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
! pip install numpy # yeh install global envrinoment 

ERROR: Invalid requirement: '#'

[notice] A new release of pip is available: 23.2.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
# pip install numpy
print("hello world")

hello world


In [4]:
#python -m venv
#venv\Scripts\activate
#deactivate
import numpy as np
np.__version__

'2.4.6'

In [5]:
print("shraddha")

shraddha


### Numpy
NumPy is a Python library used for numerical and mathematical operations. It provides support for fast multidimensional arrays and various mathematical functions.

**Types of NumPy Arrays**

NumPy mainly has these types of arrays:

| Type of Array | Dimension       | Description                       | Example           |
| ------------- | --------------- | --------------------------------- | ----------------- |
| 1D Array      | One Dimension   | Contains elements in a single row | `[1, 2, 3, 4]`    |
| 2D Array      | Two Dimension   | Contains rows and columns         | `[[1,2],[3,4]]`   |
| 3D Array      | Three Dimension | Collection of 2D arrays           | `[[[1,2],[3,4]]]` |


In [6]:
lst =(list(range(1,20)))

In [7]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [8]:
type(lst)

list

In [9]:
arr =np.array(lst)

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [11]:
lst = [1,2,3,4,5]
arr = np.array(lst)
arr

array([1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr =np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [16]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [17]:
#2D array
arr = np.zeros((2,3))#2 rows and 3 columns
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
arr =np.zeros((2,3))
print(arr.ndim) #number of dimensions

2


In [19]:
arr =np.linspace(1,10,5) #start,stop,number of elements
print(arr)
print(type(arr))

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>


In [20]:
arr = np.arange(1,30)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
#arr = np.reshape()
arr = np.arange(0,30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
arr=arr.reshape(10,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [23]:
arr=arr.reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [24]:
np.random.randint(1,5,10) #start,stop,number of elements

array([2, 2, 3, 2, 1, 3, 2, 4, 4, 2], dtype=int32)

In [25]:
arr = np.random.randint(1,5,(5,6))
arr 

array([[4, 2, 4, 4, 4, 2],
       [3, 3, 2, 1, 2, 4],
       [3, 2, 1, 1, 1, 2],
       [2, 2, 4, 3, 4, 1],
       [1, 3, 2, 3, 3, 4]], dtype=int32)

In [26]:
arr=np.random.random(10)
arr

array([0.9166864 , 0.10789357, 0.1954105 , 0.00834804, 0.17560979,
       0.64732695, 0.27863805, 0.35971822, 0.38076011, 0.0535198 ])

In [27]:
arr =np.random.random((10,3))
arr

array([[0.97098221, 0.65221115, 0.20319707],
       [0.66302228, 0.28841425, 0.68288407],
       [0.92700868, 0.64516515, 0.96339563],
       [0.53599091, 0.55813555, 0.1728983 ],
       [0.94061791, 0.23334711, 0.01017992],
       [0.08860094, 0.37864146, 0.22723035],
       [0.57693541, 0.09551373, 0.05156304],
       [0.14990747, 0.85483391, 0.27726056],
       [0.40219961, 0.01748416, 0.723678  ],
       [0.88567022, 0.29778568, 0.40431509]])

In [28]:
arr=np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [29]:
print("number of array: ", arr.shape)
print("number of dim : ", arr.ndim)
print("data type: ", arr.dtype)
print("size of array: ",arr.size)

number of array:  (12, 5)
number of dim :  2
data type:  int64
size of array:  60


In [30]:
lst =[[1,2,3],[4,5,6]]
arr = np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
arr =np.array(range(1,60))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59])

In [32]:
arr = np.array(range(5,12))

In [33]:
arr

array([ 5,  6,  7,  8,  9, 10, 11])

In [34]:
arr =np.arange(60).reshape(12,5)
arr.shape
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [35]:
#arr.transpose elment
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [36]:
#2D array ka sathe indexing and slicing
#arr[0,0]# 0 row 0 column ka element

In [37]:
arr[9:11, 3:4] #9 row 0 and 1 column ka element

array([[48],
       [53]])

In [38]:
arr[9:10, 3:4] #9 row 0 and 1 column ka element


array([[48]])

In [39]:
arr[0:9,3:5] #0 to 8 row and 3 and 4 column ka element

array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19],
       [23, 24],
       [28, 29],
       [33, 34],
       [38, 39],
       [43, 44]])

In [40]:
arr[-1,-1] =100
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58, 100]])

In [41]:
#arr[0][0]

In [42]:
arr[11,4]

np.int64(100)

In [43]:
arr[11,-1]

np.int64(100)

In [44]:
arr[-1,-1]

np.int64(100)

In [45]:
arr[-1,]

array([ 55,  56,  57,  58, 100])

In [46]:
arr[-1,-1] =100
arr

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58, 100]])

In [47]:
print("number of array: ", arr.shape)
print("number of dim : ", arr.ndim)
print("data type: ", arr.dtype)
print("size of array: ",arr.size)

number of array:  (12, 5)
number of dim :  2
data type:  int64
size of array:  60


In [48]:
# 3D array

arr = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr = np.arange(225).reshape(5,15,3)
print(arr)

[[[  0   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]
  [ 12  13  14]
  [ 15  16  17]
  [ 18  19  20]
  [ 21  22  23]
  [ 24  25  26]
  [ 27  28  29]
  [ 30  31  32]
  [ 33  34  35]
  [ 36  37  38]
  [ 39  40  41]
  [ 42  43  44]]

 [[ 45  46  47]
  [ 48  49  50]
  [ 51  52  53]
  [ 54  55  56]
  [ 57  58  59]
  [ 60  61  62]
  [ 63  64  65]
  [ 66  67  68]
  [ 69  70  71]
  [ 72  73  74]
  [ 75  76  77]
  [ 78  79  80]
  [ 81  82  83]
  [ 84  85  86]
  [ 87  88  89]]

 [[ 90  91  92]
  [ 93  94  95]
  [ 96  97  98]
  [ 99 100 101]
  [102 103 104]
  [105 106 107]
  [108 109 110]
  [111 112 113]
  [114 115 116]
  [117 118 119]
  [120 121 122]
  [123 124 125]
  [126 127 128]
  [129 130 131]
  [132 133 134]]

 [[135 136 137]
  [138 139 140]
  [141 142 143]
  [144 145 146]
  [147 148 149]
  [150 151 152]
  [153 154 155]
  [156 157 158]
  [159 160 161]
  [162 163 164]
  [165 166 167]
  [168 169 170]
  [171 172 173]
  [174 175 176]
  [177 178 179]]

 [[180 181 182]
  [183 184 185]


In [50]:
#indexing or slicing 
arr[0]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44]])

In [ ]:
arr[0][0][0] #0 row 0 column 0 element first element of first row of first 2D array

np.int64(0)

In [ ]:
arr[-1]# last element

array([[180, 181, 182],
       [183, 184, 185],
       [186, 187, 188],
       [189, 190, 191],
       [192, 193, 194],
       [195, 196, 197],
       [198, 199, 200],
       [201, 202, 203],
       [204, 205, 206],
       [207, 208, 209],
       [210, 211, 212],
       [213, 214, 215],
       [216, 217, 218],
       [219, 220, 221],
       [222, 223, 224]])

In [53]:
arr[-1,-1,-1]

np.int64(224)

In [54]:
arr[-1][-1]

array([222, 223, 224])

In [55]:
arr.shape

(5, 15, 3)

In [56]:
arr[0,0]

array([0, 1, 2])

In [57]:
arr[0:4,0]

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137]])

In [ ]:
arr[0:5,0]# phela element chaiya to 0 

array([[  0,   1,   2],
       [ 45,  46,  47],
       [ 90,  91,  92],
       [135, 136, 137],
       [180, 181, 182]])

In [59]:
arr[1:5,0:3]

array([[[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98]],

       [[135, 136, 137],
        [138, 139, 140],
        [141, 142, 143]],

       [[180, 181, 182],
        [183, 184, 185],
        [186, 187, 188]]])

In [60]:
arr[0:5,0:1,0:1]

array([[[  0]],

       [[ 45]],

       [[ 90]],

       [[135]],

       [[180]]])

In [62]:
arr

array([[[  0,   1,   2],
        [  3,   4,   5],
        [  6,   7,   8],
        [  9,  10,  11],
        [ 12,  13,  14],
        [ 15,  16,  17],
        [ 18,  19,  20],
        [ 21,  22,  23],
        [ 24,  25,  26],
        [ 27,  28,  29],
        [ 30,  31,  32],
        [ 33,  34,  35],
        [ 36,  37,  38],
        [ 39,  40,  41],
        [ 42,  43,  44]],

       [[ 45,  46,  47],
        [ 48,  49,  50],
        [ 51,  52,  53],
        [ 54,  55,  56],
        [ 57,  58,  59],
        [ 60,  61,  62],
        [ 63,  64,  65],
        [ 66,  67,  68],
        [ 69,  70,  71],
        [ 72,  73,  74],
        [ 75,  76,  77],
        [ 78,  79,  80],
        [ 81,  82,  83],
        [ 84,  85,  86],
        [ 87,  88,  89]],

       [[ 90,  91,  92],
        [ 93,  94,  95],
        [ 96,  97,  98],
        [ 99, 100, 101],
        [102, 103, 104],
        [105, 106, 107],
        [108, 109, 110],
        [111, 112, 113],
        [114, 115, 116],
        [117, 118, 11

In [68]:
#each table 3 or 4 row chaiya 
arr[0:3,2:4,0:3]

array([[[  6,   7,   8],
        [  9,  10,  11]],

       [[ 51,  52,  53],
        [ 54,  55,  56]],

       [[ 96,  97,  98],
        [ 99, 100, 101]]])

In [72]:
#each table 3 columns 4 columns chaiya
arr[0:3,0:3,2:4]

array([[[ 2],
        [ 5],
        [ 8]],

       [[47],
        [50],
        [53]],

       [[92],
        [95],
        [98]]])

In [73]:
arr[14:2]

array([], shape=(0, 15, 3), dtype=int64)

In [76]:
arr[14:-1]

array([], shape=(0, 15, 3), dtype=int64)

In [ ]:
print("number of array: ", arr.shape)
print("number of dim : ", arr.ndim)
print("data type: ", arr.dtype)
print("size of array: ",arr.size)

number of array:  (5, 15, 3)
number of dim :  3
data type:  int64
size of array:  225


In [80]:
# ==============================
# NumPy Array Operations Example
# ==============================

import numpy as np

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)

print("\n========== OPERATIONS ==========\n")

# Multiplication
print("1️⃣ Multiplication (*)")
print("arr1 * arr2 =", arr1 * arr2)

# Division
print("\n2️⃣ Division (/)")
print("arr1 / arr2 =", arr1 / arr2)

# Addition
print("\n3️⃣ Addition (+)")
print("arr1 + arr2 =", arr1 + arr2)

# Subtraction
print("\n4️⃣ Subtraction (-)")
print("arr1 - arr2 =", arr1 - arr2)

# Positive Sign with Multiplication
print("\n5️⃣ Multiplication with Unary Plus (* +)")
print("arr1 * +arr2 =", arr1 * +arr2)

# Floor Division
print("\n6️⃣ Floor Division (//)")
print("arr1 // +arr2 =", arr1 // +arr2)

print("\n✅ All operations completed successfully!")

Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]

========== OPERATIONS ==========

1️⃣ Multiplication (*)
arr1 * arr2 = [ 20  80 180 320]

2️⃣ Division (/)
arr1 / arr2 = [5. 5. 5. 5.]

3️⃣ Addition (+)
arr1 + arr2 = [12 24 36 48]

4️⃣ Subtraction (-)
arr1 - arr2 = [ 8 16 24 32]

5️⃣ Multiplication with Unary Plus (* +)
arr1 * +arr2 = [ 20  80 180 320]

6️⃣ Floor Division (//)
arr1 // +arr2 = [5 5 5 5]

✅ All operations completed successfully!


In [81]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 6, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2) 



Array 1 : [10 20 30 40]
Array 2 : [2 4 6 8]


In [ ]:
arr1.sort()

In [83]:
print("Sorted Array 1:", arr1)

Sorted Array 1: [10 20 30 40]


In [84]:
arr1 = np.array([10, 30, 20, 40])
arr2 = np.array([2, 6, 4, 8])

print("Array 1 :", arr1)
print("Array 2 :", arr2)
arr1.sort()
print("Sorted Array 1:", arr1)

Array 1 : [10 30 20 40]
Array 2 : [2 6 4 8]
Sorted Array 1: [10 20 30 40]


In [85]:
arr2.sort()
print("Sorted Array 2:", arr2)

Sorted Array 2: [2 4 6 8]


In [86]:
print("Sorted Array 1:", arr1)
print("Sorted Array 2:", arr2)

Sorted Array 1: [10 20 30 40]
Sorted Array 2: [2 4 6 8]


In [90]:
# 3D to 1D 
arr =np.arange(225)

In [91]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [92]:
arr = arr.reshape(15,15)
arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14],
       [ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44],
       [ 45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,
         58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74],
       [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104],
       [105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
        118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134],
       [135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147,
        148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
       